"""
DefectVision AI - PDF Inspection Report Generator
Generates one-page inspection reports with annotated images, defect tables, and verdicts.
"""

import io
import tempfile
from datetime import datetime
from pathlib import Path

import numpy as np
from PIL import Image
from fpdf import FPDF

from config import REPORT_TITLE


def generate_report(
    original_image: np.ndarray,
    annotated_image: np.ndarray,
    detections: list,
    summary: dict,
    severity: str,
    domain: str,
    confidence_threshold: float,
) -> bytes:
    """
    Generate a PDF inspection report.

    Args:
        original_image: Original input image (RGB numpy array)
        annotated_image: Image with detections drawn (RGB numpy array)
        detections: List of detection dicts
        summary: Dict of defect counts per type
        severity: 'pass', 'low', 'medium', or 'high'
        domain: Domain name (metal, pcb, building)
        confidence_threshold: Confidence threshold used

    Returns:
        PDF file as bytes
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, REPORT_TITLE, ln=True, align="C")
    pdf.ln(4)

    # Metadata
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.cell(0, 6, f"Domain: {domain.upper()}", ln=True)
    pdf.cell(0, 6, f"Confidence Threshold: {confidence_threshold:.2f}", ln=True)
    pdf.ln(4)

    # Verdict banner
    verdict_text = f"VERDICT: {'PASS' if severity == 'pass' else 'FAIL'} (Severity: {severity.upper()})"
    if severity == "pass":
        pdf.set_fill_color(76, 175, 80)  # green
    elif severity == "low":
        pdf.set_fill_color(255, 193, 7)  # amber
    elif severity == "medium":
        pdf.set_fill_color(255, 152, 0)  # orange
    else:
        pdf.set_fill_color(244, 67, 54)  # red

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 10, verdict_text, ln=True, align="C", fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # Annotated image
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Detection Results:", ln=True)

    # Save annotated image to temp file for PDF embedding
    with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as tmp:
        img = Image.fromarray(annotated_image)
        img.save(tmp.name, quality=90)
        # Scale image to fit page width (190mm max)
        img_width = 190
        img_height = int(img_width * img.height / img.width)
        if img_height > 120:
            img_height = 120
            img_width = int(img_height * img.width / img.height)
        pdf.image(tmp.name, x=(210 - img_width) / 2, w=img_width, h=img_height)

    pdf.ln(6)

    # Defect summary table
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"Defect Summary (Total: {len(detections)})", ln=True)

    if detections:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(70, 8, "Defect Type", border=1, align="C")
        pdf.cell(40, 8, "Count", border=1, align="C")
        pdf.cell(50, 8, "Avg Confidence", border=1, align="C")
        pdf.ln()

        pdf.set_font("Helvetica", "", 10)
        for defect_type, count in summary.items():
            # Calculate avg confidence for this defect type
            confs = [d["confidence"] for d in detections if d["class_name"] == defect_type]
            avg_conf = sum(confs) / len(confs) if confs else 0

            pdf.cell(70, 7, defect_type, border=1)
            pdf.cell(40, 7, str(count), border=1, align="C")
            pdf.cell(50, 7, f"{avg_conf:.2%}", border=1, align="C")
            pdf.ln()
    else:
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 8, "No defects detected.", ln=True)

    pdf.ln(6)

    # Individual detections
    if detections:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Detailed Detections:", ln=True)
        pdf.set_font("Helvetica", "", 9)
        for i, det in enumerate(detections[:20], 1):  # cap at 20
            bbox = det["bbox"]
            pdf.cell(
                0, 6,
                f"  {i}. {det['class_name']} - Confidence: {det['confidence']:.2%} - "
                f"Location: ({bbox[0]}, {bbox[1]}) to ({bbox[2]}, {bbox[3]})",
                ln=True,
            )

    # Footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, "Generated by DefectVision AI | Hackathon 2026", ln=True, align="C")

    # Return PDF as bytes
    return pdf.output()
